name: NASA Project CI
on : 
 push: 
  branches: [ main ]
jobs:
 build:
  env:
    CI: true
  runs-on: windows-latest
  steps:
    - uses: actions/checkout@v2
    - name: Use node version 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - run: npm install
    - run: npm run build --prefix client
    - run: npm run test